language: ruby

env:
    - LINUXBREW_HOME=$HOME/.linuxbrew PATH=$LINUXBREW_HOME/bin:$PATH

rvm:
    - 2.2

branches:
    only:
        - dev

install:
    - "git clone https://github.com/Linuxbrew/brew.git $LINUXBREW_HOME"
    - "brew update"

script:
    - "brew audit --strict --online $TRAVIS_BUILD_DIR/Formula/*"
